Repository pyreverte/MiniJeuAndroid, pull requests merged in 2021-03, with the labels that each got.

#12 Update README
  README.md
Labels: documentation

#13 Merge Develop
  .github/workflows/gradle.yml
  README.md
  app/src/androidTest/java/helloandroid/m2dl/minijeuandroid/ExampleInstrumentedTest.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameThread.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameView.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/MainActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/SystemTheme.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/Zone.java
  app/src/main/res/layout/activity_main.xml
  app/src/test/java/helloandroid/m2dl/minijeuandroid/ExampleUnitTest.java
Labels: documentation, enhancement

#14 Fix Random Number
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameView.java
Labels: bug

#15 fix/random_number
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameView.java
Labels: bug

#16 Fix Loop While
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameThread.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameView.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/MainActivity.java
Labels: bug

#17 Save score¤develop
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameThread.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameView.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/MainActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/GameActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/MenuActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/ScoreActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/data/Score.java
  app/src/main/res/layout/activity_menu.xml
  app/src/main/res/layout/activity_score.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, enhancement

#23 Fix score display
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameThread.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameView.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/Zone.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/GameActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/MenuActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/ScoreActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/data/Score.java
Labels: bug

#24 Fix/cube size
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameThread.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/GameView.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/GameActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/MenuActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/ScoreActivity.java
Labels: bug, enhancement

#25 Fix project structure
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/GameActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/ScoreActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/game/GameThread.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/game/GameView.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/models/Score.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/models/SystemTheme.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/models/Zone.java
Labels: enhancement, invalid

#26 Add UserName input
  app/src/main/res/layout/snackbar_layout.xml
Labels: enhancement

#27 Add UserName input
  app/build.gradle
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/GameActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/ScoreActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/game/GameView.java
  app/src/main/res/layout/activity_score.xml
  app/src/main/res/layout/snackbar_layout.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#28 Update README
  README.md
Labels: documentation

#29 Add background change
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/MenuActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/ScoreActivity.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/game/GameThread.java
  app/src/main/java/helloandroid/m2dl/minijeuandroid/activities/game/GameView.java
Labels: enhancement
